### ISSUE TITLE
weaktables ?

### ISSUE THREAD

**Issue by zaxebo1** [moonsharp-devs/moonsharp#105]
You have said in the http://www.moonsharp.org/moonluadifferences.html = that 'weak tables are not supported'. Should we understand that statement as : 

option1) interpret it as => it is not implemented for now, but it will be implemented in future , may be many decades after

option2) interpret it as => it is not implemented and will never be implemented, because of technical difficulties/impossibility in implementing it on .NET

I think, answer may be "option2", but still I am asking it as an issue, because being a positive person and as a 'weakness' -  I still have a "weak hope" for a possibility of  "weak table" in future :-)

**Comment by zaxebo1** [comment]
On a secondary thought , "weak tables" are not that much important on me, and I can remove them from my existing scripts

**Comment by xanathar** [comment]
anyway, it's option1.5 ;)

It's something I would like to put in at some point, and there might be (not entirely sure) ways to implement them.

The Lua and .NET GC semantics are surely very different so there's no guarantee that a solution is possible at all (apart from reimplementing big parts from scratch).

One way out I see, is to create some sort of weak container objects which may be interacted as if they were tables but don't respect table semantics fully (tables have curious semantics like, for example, having stable iterators even if objects are removed, but unstable if objects are added, etc.).

**Comment by LimpingNinja** [comment]
Closing this, will evaluate enhancement requests (even closed) for next version.
