### ISSUE TITLE
Unity - Debugger crashes (was: Unity - Runtime Exceptions in Console don't display any useful context info about Lua code)

### ISSUE THREAD

**Issue by TheMightyGit** [moonsharp-devs/moonsharp#111]
This is in Unity. I've got a large string of code, but if something goes wrong at runtime I get no useful indicator as to the problematic line of code in the Console. All I get is...

ScriptRuntimeException: attempt to index a nil value
MoonSharp.Interpreter.Execution.VM.Processor.ExecIndexSet (MoonSharp.Interpreter.Execution.VM.Instruction i, Int32 instructionPtr)
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (Int32 instructionPtr)

In normal cases I can catch this exception myself and pull out the useful info, but I use a lot of events - and there doesn't seem to be a way for me to catch exceptions thrown by code that gets called by an event.

There is perhaps a way in Unity that I can catch this and turn it into something more useful, but a better (?) fix may be to include the line number in the exception when it's thrown? Even "attempt to index a nil value at line 123" would be a massive help.

I tried using the remote debugger, but Unity crashes when I load a new scene :(

**Comment by xanathar** [comment]
There is a "DecoratedMessage" property in every exception which has the script location of the error, including columns and lines range. It's possible to get just the line instead of the whole range details (less detailed but more easily readable) by setting Script.Options.UseLuaErrorLocations to true.

Let me know if this helps.

On the other hand - the remote debugger things sounds like a bad bug! Thanks for reporting, I'll dig into it!

**Comment by TheMightyGit** [comment]
I'm now wrapping all my event invocations and .Resume calls in a try/catch to display the DecoratedMessage (which has useful info. yay!)

MoonSharp is awesome, btw :) Super happy with using it in my game.

**Comment by xanathar** [comment]
>> MoonSharp is awesome, btw :) Super happy with using it in my game.

Thanks! :) Super happy of receiving comments like these :)

**Comment by LimpingNinja** [comment]
Not sure why this is open, if closing is a mistake please reopen.
