### ISSUE TITLE
Consider Universal Windows Platform support

### ISSUE THREAD

**Issue by XamlBrewer** [moonsharp-devs/moonsharp#116]
I added Windows 10 as a target in your PCL project source, and recompiled. I referenced it in a Windows Universal app and did some testing. It seems so work properly.

You may want to consider upgrading the NuGet package to support this platform.

**Comment by xanathar** [comment]
So far the PCL project is trying to target the minimum versions for the biggest portability to avoid proliferating thousands of versions..

My ignorance here, as I haven't downloaded VS2015 and stuff yet.. doesn't the win8 platform work for Windows 10 apps ?

**Comment by galich** [comment]
Just FYI - I'm using Moonsharp in UWP project with no issues, great job @xanathar !
