### ISSUE TITLE
PlatformAutoDetector consumes huge amount of memory

### ISSUE THREAD

**Issue by kamend** [moonsharp-devs/moonsharp#125]
For some reason PlatformAutoDetector, consumes around ~1mb of memory on iOS and Unity. Probably because of the Linq query inside, but is there some way we could bypass this?

**Comment by xanathar** [comment]
PlatformAutoDetector is one of the very first things to be executed.. are you sure that 1MB is not counting code loaded, code JITted, etc. ?

**Comment by LimpingNinja** [comment]
No update on this, stale issue. Closed.
