### ISSUE TITLE
how debug script more times

### ISSUE THREAD

**Issue by gitlsl** [moonsharp-devs/moonsharp#138]
`
        RemoteDebuggerService remoteDebugger;

```
    private int i = 0;
    private void ActivateRemoteDebugger(Script script)
    {
        remoteDebugger = new RemoteDebuggerService(new RemoteDebuggerOptions()
        {
            NetworkOptions = Utf8TcpServerOptions.LocalHostOnly | Utf8TcpServerOptions.SingleClientOnly,
            SingleScriptMode = true,
            HttpPort = 2705 + i++,
            RpcPortBase = 2006,
        });
        remoteDebugger.Attach(script, "Description of the script", false);
        Process.Start(remoteDebugger.HttpUrlStringLocalHost);
    }
    string MoonSharpFactorial()
    {
        Script script = new Script();
        ActivateRemoteDebugger(script);
        var ret = script.DoString(@"
                                    a=1
                                    b=2
                                    return a+b
                                    ");
        return ret.ToString();
    }

    private void onClick(object sender, EventArgs e)
    {
        MoonSharpFactorial();
    }`
```

this is my code   when I click second time  there will be a mistake? how do I debug script right?

3q!

**Comment by gitlsl** [comment]
and  for " remoteDebugger.Attach(script, "Description of the script", false);" if set  false  to true ,  the script will not be blocked,return result directly

**Comment by xanathar** [comment]
Regarding your second comment, that's exactly what the boolean parameters is for - if set to true, the script does not wait the debugger and just runs. 

Regarding the first comment.. I don't understand the question, what problem are you having ?

**Comment by gitlsl** [comment]
@xanathar My mean is    When I click button twice   debug also twice , but it will be wrong when second click?

**Comment by LimpingNinja** [comment]
Not enough info, did not replicate. If this is still valid, please attach working repro to issue.
