### ISSUE TITLE
Yield from within C# code

### ISSUE THREAD

**Issue by Fraysa** [moonsharp-devs/moonsharp#142]
I have a method in C# that sends a message to the Console and I use that method in my scripts. How can I yield the script from wirhin C# code and not through the script?

Script is:

```
-- This is a test for Rajan Grewal De Patel De 1st!
return function()
    send("hey");
    coroutine.yield();
    send("heyyy");
end
```

I want to call yield from within C# and not the script, how can it be done?

**Comment by xanathar** [comment]
Any C# function returning DynValue.NewYieldReq(...) does cause a yield on the current calling Lua coroutine - if this answers your question.

**Comment by LimpingNinja** [comment]
Beyond the answer given above and the data at https://www.moonsharp.org/coroutines.html, this appears like it is answered.

**Comment by noahcgreen** [comment]
Is it possible for a C# function called from Lua to cause multiple yields on the calling coroutine? My goal is to write a function in C# which can be used as a coroutine function within the Lua environment. Requiring the function to return a DynValue.NewYieldReq seems to mandate that the function can only yield once.

**Comment by IS4Code** [comment]
I have thought using `NewTailCallReq` would work in this case if the called function yielded, but it seems it's not, at least in the nuget version I tried to use:

```cs
static void Main(string[] args)
{
    Script script = new Script();
    script.Globals["myFunc"] = new CallbackFunction(Callback);
    script.DoString(@"
local c = coroutine.create(function(...)return myFunc(...)end)
print('From c:', coroutine.resume(c, 1, 2, 3))
print('From c:', coroutine.resume(c, 4, 5, 6))
print('From c:', coroutine.resume(c, 7, 8, 9))
");
}

static DynValue Callback(ScriptExecutionContext ctx, CallbackArguments args)
{
    var print = ctx.CurrentGlobalEnv.Get("print");
    var pArgs = new DynValue[args.Count + 1];
    pArgs[0] = DynValue.NewString("In c:");
    args.GetArray().CopyTo(pArgs, 1);
    ctx.OwnerScript.Call(print, pArgs);
    var yielding = DynValue.NewCallback(delegate
    {
        return DynValue.NewYieldReq(args.GetArray().Select(n => DynValue.NewNumber(n.Number * 10)).ToArray());
    });
    return DynValue.NewTailCallReq(new TailCallData
    {
        Function = yielding,
        Args = Array.Empty<DynValue>(),
        Continuation = new CallbackFunction(Callback)
    });
}
```

I get these results:
```
In c:   1       2       3
From c: true    10      20      30
From c: true    4       5       6
From c: false   cannot resume dead coroutine
```
Seems like the yielding does occur, but continuation is ignored.
