### ISSUE TITLE
json.parse() throw ScriptRuntimeException {"Unexpected token : '-'"}

### ISSUE THREAD

**Issue by vladzh** [moonsharp-devs/moonsharp#163]
Json example:
{"id":11,"mode":null,"x":-5.35,"y":-1.9,"a":0.0,"mx":false,"my":false}

Use MoonSharp 2.0.0.0 Version for net framework 3.5

**Comment by xanathar** [comment]
ouch!
Thanks 👍  will debug asap

**Comment by apristen** [comment]
Sorry, but it not fixed in 2.0.0.0 Version for net framework 3.5 (DLL)

But if I add fix from https://github.com/xanathar/moonsharp/pull/178/commits/22824872b422f0464b23a560e044834d4c049677 to the source - it works.

Please add it to next version.

Thanks!

**Comment by LimpingNinja** [comment]
Pull request to resolve this has been merged.
