### ISSUE TITLE
how to use json

### ISSUE THREAD

**Issue by qq1054599715** [moonsharp-devs/moonsharp#166]
code:
 Script script = new Script();
        Table t = new Table(script);
        t["OpenId"] = "IADSBKAA54563S1D3F1";
        t["NickName"] = "zyc";
        string ser= t.Serialize();
        Debug.Log(ser);

get issue:
ScriptRuntimeException: Table is not a prime table.
MoonSharp.Interpreter.Serialization.SerializationExtensions.Serialize (MoonSharp.Interpreter.Table table, Boolean prefixReturn, Int32 tabs)

**Comment by qq1054599715** [comment]
there has bug in json.

public static string Serialize(this Table table, bool prefixReturn = false, int tabs = 0)
		{
			if (table.OwnerScript != null)
				throw new ScriptRuntimeException("Table is not a prime table.");
....

the code “			if (table.OwnerScript != null)” should be if (table.OwnerScript == null)

i like moonsharp.wish it is the best forever

**Comment by qq1054599715** [comment]
and there also has the same code

	else if (dynValue.Type == DataType.Table && dynValue.Table.OwnerScript == null)
				return Serialize(dynValue.Table, false, tabs);

**Comment by bplu4t2f** [comment]
Maybe this has resolved itself by now, but `SerializationExtensions.Serialize` is *not* for JSON serialization. This is why it isn't working for you; the code was correct.

For JSON use `JsonTableConverter.TableToJson`.

From LUA:

    table = { ... }
    json.serialize(table)

From C#:

    Script script = new Script();
    Table t = new Table(script);
    t["OpenId"] = "IADSBKAA54563S1D3F1";
    t["NickName"] = "zyc";
    string ser= t.TableToJson();
    Debug.Log(ser);

**Comment by qq1054599715** [comment]
thank you

**Comment by LimpingNinja** [comment]
Thanks @bplu4t2f  for the answer here.
