### ISSUE TITLE
json deserialize bug

### ISSUE THREAD

**Issue by qq1054599715** [moonsharp-devs/moonsharp#167]
json string：

{"NetID":2,"UserData":[{"Index":0,"CurCard":0,"CardCurrent":[35,35,35,35,36,37,36],"CardExtent":[0,24,0,18],"CardSend":[11,12,13,19,17,23,14,41,38,25,29,34,23],"TotalScore":0,"Score":-2,"FangGangCount":0,"NetID":1},{"Index":0,"CurCard":11,"CardCurrent":[28,28,28,11],"CardExtent":[0,22,0,26,0,31],"CardSend":[15,16,21,19,32,27,29,37,39,29,13,39,19,23,14],"TotalScore":0,"Score":6,"FangGangCount":0,"NetID":2},{"Index":0,"CurCard":0,"CardCurrent":[12,12,21,22,23,27,28,32,33,36,38,39,41],"CardExtent":[],"CardSend":[33,34,33,14,37,38,26,34,13,17,39,15,41],"TotalScore":0,"Score":-2,"FangGangCount":0,"NetID":3},{"Index":0,"CurCard":0,"CardCurrent":[15,15,16,16,17,18,19,21,25,29,31,32,34],"CardExtent":[],"CardSend":[27,25,36,13,33,24,17,12,11,37,21,27,41],"TotalScore":0,"Score":-2,"FangGangCount":0,"NetID":4}],"LastCards":[32,14,16,25,38]}

get bug ：SyntaxErrorException: Unexpected token : '-'

result：
JSON moonsharp cannot recognize a negative number

**Comment by LimpingNinja** [comment]
Pull request to resolve this has been merged.
