### ISSUE TITLE
iOS App Store - Release mode issues

### ISSUE THREAD

**Issue by yosun** [moonsharp-devs/moonsharp#182]
This seems to work fine in debug non-release mode.
 
For release to App Store, this error occurs: 

"ScriptRunTimeException: Can not convert CLR type System.MonoType"
 
Is this actually not supported on AOT?

**Comment by bplu4t2f** [comment]
I just worked on something unrelated and discovered a potential issue that might have something to do with this.

Could you read `UserData.GetRegisteredTypes` and check if there is any type which you didn't explicitly register (`EventFacade`, `AnonWrapper`, `EnumerableWrapper`, `JsonNull` are fine)? Especially if something like `Object` or `Delegate` sneaks in it will cause a lot of issues.

**Comment by unitycoder** [comment]
same as this?
https://github.com/xanathar/moonsharp/issues/165

**Comment by LimpingNinja** [comment]
Quote from #165:

> Just for reference also:
> using 5.3.7p4 + moonsharp 2.0, local ios build worked fine, but had crashing with TestFlight and AppStore builds.. Solved by disabling [ ] include bitcode in xcode archive upload settings. (some details here): https://unitycoder.com/blog/2017/05/21/ios-app-crashes-only-if-downloaded-from-appstore-or-testflight/
