### ISSUE TITLE
Windows 10 support broken since v2.0.0

### ISSUE THREAD

**Issue by chkr1011** [moonsharp-devs/moonsharp#193]
Hi,
I am using the library **v1.8.0** (via nuget) and it works without any problems. My setup is an UWP app which targets Windows 10 (x86, x64, ARM) and also runs on a Rapberry Pi 2(Windows 10 IoT Core). **v1.8.0** works perfect for all build targets

But since I've updated to version **v2.0.0** (via nuget) I get the following exception when _DoString()_ is called:

> System.IO.FileLoadException: 'Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

When I revert to **v1.8.0** without any code/project changes it works again. So to me the support for Windows 10 UWP is broken since **v2.0.0**

Best regards
Christian

**Comment by wuyin1985** [comment]
i have the same issue,waiting too.

**Comment by yoshiask** [comment]
It's been fours years, we're still waiting...

**Comment by chkr1011** [comment]
Isn't it 2 years only? 😄

**Comment by chkr1011** [comment]
I assume this project is dead so I no longer expect an answer here.
