### ISSUE TITLE
Zerobrane support

### ISSUE THREAD

**Issue by tluyben** [moonsharp-devs/moonsharp#205]
I cannot find any references if there is or if anyone has got that to work. I work with VS for C# and Zerobrane for Lua and wanted to merge things with Moonsharp but find Zerobrane (my perversion, I am aware) easier to work with Lua.

**Comment by AdamFrisby** [comment]
I wrote a ZeroBrane autocomplete file for ZeroBrane - which you can find here: https://github.com/AdamFrisby/AutoDoxyBrane

**Comment by LimpingNinja** [comment]
Thanks for the answer @AdamFrisby - Closing this.
