### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by seriouz** [moonsharp-devs/moonsharp#206]
Does moonsharp support dotnet Core 2.0?

**Comment by StefanJanssen95** [comment]
I highly doubt it since the last update in this repo was in January 2017 and dotnet Core 2.0 released in August 2017.

Have you in the meantime found an alternative which does support dotnet core 2.0?

**Comment by berbun** [comment]
See my comment [here](https://github.com/moonsharp-devs/moonsharp/issues/239#issuecomment-546581171).

**Comment by LimpingNinja** [comment]
It does. Closed.
