### ISSUE TITLE
Table.Length incorrect

### ISSUE THREAD

**Issue by wledfor2** [moonsharp-devs/moonsharp#220]
In vanilla Lua, the following code outputs 5:

```
t = {1, 2, 3, nil, 4}
print(#t)
```

In moonsharp, it outputs 3, which is unexpected.

**Comment by wledfor2** [comment]
Nevermind, I just realized this makes Table.Length more reliable than Lua's.

Consider the following code:

```
t = {1, 2, 3, nil, 4}
print(#t)
for k,v in pairs(t) do print(k .. " = " .. v) end
```

In MoonSharp, the output is:
3
1 = 1
2 = 2
3 = 3
5 = 4

in Lua, the output is:
5
1 = 1
2 = 2
3 = 3
5 = 4

I would rather have false negatives than false positives. Good work.

**Comment by Benjamin-Dobell** [comment]
I'm reopening this because the behaviour is incorrect. Consider:

Lua REPL
```lua
> t = {}
> table.insert(t, 1, nil)
> print(#t)
0
```

MoonSharp REPL
```lua
> t = {}
> table.insert(t, 1, nil)
> print(#t)
1
```

I plan to correct this (at some stage).

**Comment by Benjamin-Dobell** [comment]
Actually, going to create a separate issue. Regular Lua's behaviour in this example is _super_ weird though.
