### ISSUE TITLE
Creating a second MoonSharpVsCodeDebugServer causes socket exception

### ISSUE THREAD

**Issue by Azagatoth** [moonsharp-devs/moonsharp#223]
When I create a second debugging session using MoonSharpVsCodeDebugServer I get a socket exception.
When the first session finishes I call the following code:

        protected void CleanUpLua()
        {
            if (debugServer != null)
            {
                debugServer.Detach(luaScript);
                debugServer.Dispose();
                debugServer = null;
            }
        }

Can anyone please explain, what I should be doing to get this to work.
The above does not do the trick, even though the Dispose should exit the ListenThread while loop.

**Comment by Azagatoth** [comment]
SocketException:
Only one usage of each socket address (protocol/network address/port) is normally permitted:
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at MoonSharp.VsCodeDebugger.MoonSharpVsCodeDebugServer.Start() in Z:\git\my\moonsharp\src\MoonSharp.VsCodeDebugger\MoonSharpVsCodeDebugServer.cs:line 220

**Comment by komodo472** [comment]
@Azagatoth It's been a while since you asked but hopefully this will help you and anyone else who comes across this problem. I was having this same issue and I found that I was calling server.start() again before the OS/Moonsharp had finished closing the socket. Your code should work, my assumption would be that the OS was still cleaning up the connection when you call server.start() again. I ended up writing some code to retry the connection every second until the socket was either freed up or took too long. I wrote this for Unity so you may have to adjust this for your needs. Hope this helps!

```
private void ActivateVsCodeDebugger(Script script)
{
    if (vsCodeServer != null)
    {
        vsCodeServer.Detach(script);
        vsCodeServer.Dispose();
        vsCodeServer = null;
    }

    // Create the debugger server
    vsCodeServer = new MoonSharpVsCodeDebugServer();
    // Start the debugger server
    int retries = 0;
    int maxRetries = 5;
    while (retries != maxRetries)
    {
        try
        {
            vsCodeServer.Start();
            retries = 5;
        }
        catch (SocketException se)
        {
            Debug.Log("SocketException! Try: " + retries.ToString());
            if (se.ErrorCode == 10048)
            {
                Debug.Log("Failed to start Debugger! " + se.ErrorCode.ToString() + " - " + se.Message);
                Debug.Log("Retrying in 1 second!");
                System.Threading.Thread.Sleep(1000);
            }
            else
            {
                Debug.LogError("Cannot start debugger! Unhandled Error: " + se.ErrorCode.ToString() + " - " + se.Message);
            }

            if (retries == maxRetries)
            {
                throw new Exception("Failed to start Debugger!");
            }

            retries++;
            }
        }
        // Attach the script to the debugger
        vsCodeServer.AttachToScript(script, "My Awsome Debugger");
}
```

**Comment by Azagatoth** [comment]
@komodo472 Thank you for your very elaborate answer. 
I ended up writing my own version that made sure the socked was properly closed on dispose.
My problem is that the vsCodeServer (as in your example) is disposed and created again, but keeps the socket connection open.
I do not have the option to keep it in memory, since the code is running in a thread (Task) that is killed as soon as it is finished running the job.

**Comment by LimpingNinja** [comment]
Thanks for the answer, @komodo472
