### ISSUE TITLE
Can't get hardwiring to work

### ISSUE THREAD

**Issue by Sajdkick** [moonsharp-devs/moonsharp#234]
Hey!

I love Moonsharp and it works great so far, but the scripting is becoming somewhat of a bottleneck. I checked out the tutorial on hardwiring on the website, but i can't figure out the second step.  How do i generate the code using 'moonsharp -W c:\temp\testdump.lua c:\temp\out.cs --internals --class:MyClass --namespace:MyNamespace'?

Been at it the whole day but i must admit defeat. Any help or pointers to where i can read more about hardwiring is much appreciated! Thanks!

**Comment by Sajdkick** [comment]
Bump, i'm still trying to get this to work. I'm still totally clueless to where to run the 'moonsharp -W c:\temp\testdump.lua c:\temp\out.cs --internals --class:MyClass --namespace:MyNamespace' command.

**Comment by Ro4m3r** [comment]
Download the MoonSharp release, inside will be a folder named "repl" that contains a "MoonSharp.exe". Run your cmd prompt from wherever that .exe is, or drop it in windows/system32 so command prompt will automatically find it, allowing you to run it from anywhere.

**Comment by Sajdkick** [comment]
Awesome thanks! I'll try it out on monday at work, had almost given up hope that i would get any lead on how to do this!
