### ISSUE TITLE
'error' function not fully implemented, despite website saying it is

### ISSUE THREAD

**Issue by ixjf** [moonsharp-devs/moonsharp#237]
The 'error' function in Lua is not fully implemented, despite http://www.moonsharp.org/MoonSharpStdLib.pdf saying it is. It does not handle the second parameter 'level'.

**Comment by xanathar** [comment]
Merged PR.

**Comment by Ayplow** [comment]
`error` still isn't fully implemented - try

```lua
print(pcall(function() error(0) end)) --> false   stdin:1: 0
```

https://github.com/moonsharp-devs/moonsharp/blob/7b8103d58b30c72f7122c9c20ec682f0066e635f/src/MoonSharp.Interpreter/CoreLib/BasicModule.cs#L87

causes this code to complain about the argument that was passed to `error`. (It's worth noting that `error()` is considered equivalent to `error(nil)`)

**Comment by ixjf** [comment]
Indeed, the documentation for the error function is not very clear. The first parameter does not necessarily have to be a string, and it doesn't seem to be required at all either.
