### ISSUE TITLE
.NET Standard NuGet

### ISSUE THREAD

**Issue by blakepell** [moonsharp-devs/moonsharp#268]
I'm glad to see there is some momentum gaining on this project.  Great news. :)

Is there going to be a new release anytime in the near future with .NET Standard targets?  The current release on NuGet is from 2016 (and can't be used with .NET Core 3 or UWP apps).  I have a fork that I'm using that targets netstandard2.0 but would prefer to use the official release.

**Comment by Benjamin-Dobell** [comment]
We're working on it: https://github.com/moonsharp-devs/moonsharp/tree/wip/modern_build

However, if you could kindly use the [Discord](https://discord.gg/HRNCdah) for questions in future, that would be very much appreciated.

**Comment by blakepell** [comment]
Didn't realize there was a Discord until now, will use that in the future.  Thanks.
