### ISSUE TITLE
Feature Request: AST API

### ISSUE THREAD

**Issue by felaugmar** [moonsharp-devs/moonsharp#269]
Expression tree generation is mostly internal as stated in #152 and not documented.

There are probably reasons to be internal like that, but it could be exposed without much effort?

**Comment by Benjamin-Dobell** [comment]
I don't think this an unreasonable request. However, there are presently no plans to do so. If you were to work on it and submit a pull request I'm sure it would be considered.

**Comment by felaugmar** [comment]
I did some investigation in the code and indeed, it's well organized and even though it's a lot of code, it's not that hard to build an **AST** while the parser is going.

I'll implement it and see if it goes well.

**Comment by felaugmar** [comment]
It was probably a bigger challenge than I expected in the past. 😕 

I'm not using Moonsharp anymore, so I'll close this issue, reopen if needed.
