### ISSUE TITLE
Bug with io.open

### ISSUE THREAD

**Issue by therudy** [moonsharp-devs/moonsharp#272]
Hello,

I have a problem with io.open

with :

f = io.open('test.txt', 'w')
f:write(Fight_Map .. "\n")
f:close()

its work fine,

but if i change "w" for "a" append , 
i get : 
Impossible de lire le script : MoonSharp.Interpreter.ScriptRuntimeException: attempt to index a nil value
   à MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex(Instruction i, Int32 instructionPtr)
   à MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr)
   à MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args)
   à MoonSharp.Interpreter.Script.Call(DynValue function, DynValue[] args)
   à MoonSharp.Interpreter.Script.Call(Object function)
   à SwiftBotTouch.Readscript.ThreadScript()

any idea how to fix it ?

thank you

sorry for my english

**Comment by Benjamin-Dobell** [comment]
Fixed by https://github.com/moonsharp-devs/moonsharp/commit/5e313e47d516dfd8a567e1dea5e676d269f79216 on the `wip/modern_build` branch.
